language: node_js
node_js:
  - 'stable'
  - 'lts/*'
  - '10'
script:
  - npm run build
after_script:
  - ls -lh dist/*
deploy:
  provider: releases
  name: 'prebuilt p2p-local-network-chat binaries'
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  on:
    branch: master
    node: stable
  file: dist/*
  file_glob: true

